### ISSUE TITLE
some assertAlmostEqual tests break with newer libs

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/pyminc#27]
python 3.6.2, numpy 1.13.1

five failures of the following form:

```
======================================================================
ERROR: testFromFileDataByte (test.generatorTests.TestFromFile)
ensure that byte data is read correct with a precision of 8 decimals on a call to aveage()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/axiom2/projects/software/arch/linux-xenial-xerus/src/pyminc/test/generatorTests.py", line 187, in testFromFileDataByte
    self.assertAlmostEqual(a, output, 8)
  File "/axiom2/projects/software/arch/linux-xenial-xerus/python/3.6.2/lib/python3.6/unittest/case.py", line 870, in assertAlmostEqual
    if round(abs(second-first), places) == 0:
TypeError: type HyperSlab doesn't define __round__ method

======================================================================
```

**Comment by bcdarwin** [comment]
Fixed in 0.52.
