### ISSUE TITLE
sporadic test failures

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/pyminc#34]
e.g.,

```
Executing pytestCheckPhase
============================= test session starts ==============================
platform linux -- Python 3.7.9, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /build/source
collected 101 items                                                            

test/generatorTests.py ................................................. [ 49%]
..................................F.FF.../build/source/libsrc2/volume.c:1609 (from miclose): Error: Trying to close null volume
Exception ignored in: <function mincVolume.__del__ at 0x7fffde173b00>
Traceback (most recent call last):
  File "/build/source/pyminc/volumes/volumes.py", line 781, in __del__
    self.closeVolume()
  File "/build/source/pyminc/volumes/volumes.py", line 768, in closeVolume
    testMincReturn(r)
  File "/build/source/pyminc/volumes/volumes.py", line 21, in testMincReturn
    raise mincException
pyminc.volumes.volumes.mincException:
/build/source/libsrc2/volume.c:1609 (from miclose): Error: Trying to close null volume
Exception ignored in: <function mincVolume.__del__ at 0x7fffde173b00>
Traceback (most recent call last):
  File "/build/source/pyminc/volumes/volumes.py", line 781, in __del__
    self.closeVolume()
  File "/build/source/pyminc/volumes/volumes.py", line 768, in closeVolume
    testMincReturn(r)
  File "/build/source/pyminc/volumes/volumes.py", line 21, in testMincReturn
    raise mincException
pyminc.volumes.volumes.mincException:
F.........                      [100%]

=================================== FAILURES ===================================
______________________ TestHyperslabs.testHyperslabArray _______________________

self = <test.generatorTests.TestHyperslabs testMethod=testHyperslabArray>

    def testHyperslabArray(self):
        """hyperslab should be reinsertable into volume"""
        v = volumeFromFile(inputFile_ushort)
        o = volumeFromInstance(v, outputFilename, data=False)
        hyperslab = v.getHyperslab((10,0,0), (1, v.sizes[1], v.sizes[2]))
        hyperslab = hyperslab * 100
        o.setHyperslab(hyperslab, (10,0,0))
        o.writeFile()
        v2 = volumeFromFile(outputFilename)
        h2 = v2.getHyperslab((10,0,0), (1, v2.sizes[1], v2.sizes[2]))
        v2.closeVolume()
>       self.assertAlmostEqual(np.average(hyperslab), np.average(h2), 8)
E       TypeError: type HyperSlab doesn't define __round__ method

test/generatorTests.py:945: TypeError
_______________________ TestHyperslabs.testSetHyperslab ________________________

self = <test.generatorTests.TestHyperslabs testMethod=testSetHyperslab>

    def testSetHyperslab(self):
        """setting hyperslab should change underlying volume"""
        v = volumeFromFile(inputFile_ushort)
>       o = volumeFromInstance(v, outputFilename, data=False)

test/generatorTests.py:925:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pyminc/volumes/factory.py:17: in volumeFromInstance
    v.createVolumeHandle(volumeType or volInstance.volumeType)
pyminc/volumes/volumes.py:700: in createVolumeHandle
    testMincReturn(r)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

value = -1

    def testMincReturn(value):
        if value < 0:
>           raise mincException
E           pyminc.volumes.volumes.mincException

pyminc/volumes/volumes.py:21: mincException
----------------------------- Captured stderr call -----------------------------
/build/source/libsrc2/volume.c:232 (from miclose): Unable to create file '/build/test-out-b6o062iu.mnc'
_____________________ testVectorFiles.testReduceDimensions _____________________

self = <test.generatorTests.testVectorFiles testMethod=testReduceDimensions>

    def testReduceDimensions(self):
        """ensure that vector file can be turned into spatial volume"""
        v = volumeFromFile(inputVector)
>       v2 = volumeFromInstance(v, outputFilename, dims=["xspace", "yspace", "zspace"])

test/generatorTests.py:963:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pyminc/volumes/factory.py:17: in volumeFromInstance
    v.createVolumeHandle(volumeType or volInstance.volumeType)
pyminc/volumes/volumes.py:700: in createVolumeHandle
    testMincReturn(r)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

value = -1

    def testMincReturn(value):
        if value < 0:
>           raise mincException
E           pyminc.volumes.volumes.mincException

pyminc/volumes/volumes.py:21: mincException
----------------------------- Captured stderr call -----------------------------
/build/source/libsrc2/volume.c:232 (from miclose): Unable to create file '/build/test-out-b6o062iu.mnc'
________________ testDirectionCosines.testDirCosVolumeFromData _________________

self = <test.generatorTests.testDirectionCosines testMethod=testDirCosVolumeFromData>

    def testDirCosVolumeFromData(self):
        """test creating a volume with direction cosines using volumeFromData"""
        x0 = 0.8476348547
        x1 = 0.2164954895
        x2 = 0.2534970854
        y0 = 0.1232442363
        y1 = 0.7664544689
        y2 = 0.0047723742
        z0 = 0.1784390237
        z1 = 0.4534233971
        z2 = 0.8564847453
        data_block = np.arange(24000).reshape(20,30,40)
        v = volumeFromData(outputFilename, data_block,
                           dimnames=("xspace", "yspace", "zspace"),
                           starts=(0, 0, 0),
                           steps=(1, 1, 1),
                           volumeType="int",
                           x_dir_cosines=(x0, x1, x2),
                           y_dir_cosines=(y0, y1, y2),
>                          z_dir_cosines=(z0, z1, z2))

test/generatorTests.py:1159:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pyminc/volumes/factory.py:71: in volumeFromData
    z_dir_cosines=z_dir_cosines)
pyminc/volumes/factory.py:48: in volumeFromDescription
    v.createVolumeHandle(volumeType)
pyminc/volumes/volumes.py:700: in createVolumeHandle
    testMincReturn(r)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

value = -1

    def testMincReturn(value):
        if value < 0:
>           raise mincException
E           pyminc.volumes.volumes.mincException

pyminc/volumes/volumes.py:21: mincException
----------------------------- Captured stderr call -----------------------------
/build/source/libsrc2/volume.c:232 (from miclose): Unable to create file '/build/test-out-b6o062iu.mnc'
=========================== short test summary info ============================
FAILED test/generatorTests.py::TestHyperslabs::testHyperslabArray - TypeError...
FAILED test/generatorTests.py::TestHyperslabs::testSetHyperslab - pyminc.volu...
FAILED test/generatorTests.py::testVectorFiles::testReduceDimensions - pyminc...
FAILED test/generatorTests.py::testDirectionCosines::testDirCosVolumeFromData
========================= 4 failed, 96 passed in 4.99s =========================
/build/source/libsrc2/volume.c:1609 (from miclose): Error: Trying to close null volume
Exception ignored in: <function mincVolume.__del__ at 0x7fffde173b00>
Traceback (most recent call last):
  File "/build/source/pyminc/volumes/volumes.py", line 781, in __del__
    self.closeVolume()
  File "/build/source/pyminc/volumes/volumes.py", line 768, in closeVolume
    testMincReturn(r)
  File "/build/source/pyminc/volumes/volumes.py", line 21, in testMincReturn
    raise mincException
pyminc.volumes.volumes.mincException:
```

**Comment by bcdarwin** [comment]
Anyway, we should probably use `numpy.testing.assert_allclose`.

**Comment by bcdarwin** [comment]
Also this:

```
=================================== FAILURES ===================================
_________________________ TestReadWrite.testReadWrite __________________________

self = <test.generatorTests.TestReadWrite testMethod=testReadWrite>

    def testReadWrite(self):
        """ensure that data can be read and written correctly"""
        v = volumeFromFile(inputFile_ushort)
        o = volumeFromInstance(v, outputFilename, data=True)
        #print(o.data)
        o.data = v.data * 5
        oa = np.average(o.data)
        v.closeVolume()
        o.writeFile()
        o_back_in = volumeFromFile(outputFilename)
        o_back_in_a = np.average(o_back_in.data)
        o_back_in.closeVolume()
>       self.assertAlmostEqual(o_back_in_a, oa, 8)
E       TypeError: type HyperSlab doesn't define __round__ method

test/generatorTests.py:885: TypeError
=========================== short test summary info ============================
FAILED test/generatorTests.py::TestReadWrite::testReadWrite - TypeError: type...
========================= 1 failed, 99 passed in 4.66s =========================
```

**Comment by bcdarwin** [comment]
See also #27.
